#! /bin/bash
termux-wake-lock
clear

update () {
  pkg upgrade -y
  python -m pip install --upgrade pip
  pip install -U yt-dlp
  pip install auto-editor --upgrade
  pkg autoclean
}

audioPodcast () {
  title=`yt-dlp --print filename -o "%(title)s.m4a" $url --restrict-filenames`
  cd ~/storage/music/Podcasts/
  yt-dlp -f 'ba' -x --audio-format m4a $url -o '%(title)s.m4a' --sponsorblock-remove all --throttled-rate $rate --concurrent-fragments $fragments --retries infinite --embed-thumbnail
}

audioMusic () {
  title=`yt-dlp --print filename -o "%(title)s.m4a" $url --restrict-filenames`
  cd ~/storage/music/Music/
  yt-dlp -f 'ba' -x --audio-format m4a $url -o '%(title)s.%(ext)s' --sponsorblock-remove all --throttled-rate $rate --concurrent-fragments $fragments --retries infinite --embed-thumbnail
}

video () {
  title=`yt-dlp --print filename -o "%(title)s" $url --restrict-filenames`
  cd ~/storage/movies/Videos/
	yt-dlp -f "bv+ba/b" $url -o '%(title)s.%(ext)s' --sponsorblock-remove all --throttled-rate $rate --concurrent-fragments $fragments --retries infinite --embed-thumbnail --write-subs --write-auto-subs --embed-subs --compat-options no-keep-subs
}

videoSilenceRemove () {
  title=`yt-dlp --print filename -o "%(title)s" $url --restrict-filenames`
  cd ~/storage/movies/Videos/
  auto-editor $url --my-ffmpeg --ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg --no-open --margin 0.2sec -o $title --yt-dlp-extras "--sponsorblock-remove all --throttled-rate 150K --concurrent-fragments 10 --retries infinite --embed-thumbnail --write-subs --write-auto-subs --embed-subs --compat-options no-keep-subs"
  find  . -name 'http*' -exec rm {} \;
}

whatUpdate () {
  echo "1. Only Update"
  echo "a. Update and Audio"
  echo "b. Update and Video"
  read m
  if [ "$m" = '1' ]; then
    update
  else
  if [ "$m" = "a" ]; then
    echo "a. Podcast"
    echo "b. Music"
    read x
    if [ "$x" = "a" ]; then
      update
      audioPodcast
    else
    if [ "$x" = "b" ]; then
      update
      audioMusic
    else
      :
    fi
    fi
  else
  if [ "$m" = "b" ]; then
    echo "a. Video"
    echo "b. Video Removed Silence"
    read x
    if [ "$x" = "a" ]; then
      update
      video
    else
    if [ "$x" = "b" ]; then
      update
      videoSilenceRemove
    else
      :
    fi
    fi
  else
    cd ~/bin
  	./termux-url-opener $url
  fi
  fi
  fi
}

url=$1
rate=150K
fragments=10

echo "1. Update"
echo "a. Audio"
echo "b. Video"
read n

if [ "$n" = '1' ]; then
	whatUpdate
else

if [ "$n" = "a" ]; then
    echo "a. Podcast"
    echo "b. Music"
    read x
    if [ "$x" = "a" ]; then
      audioPodcast
    else
    if [ "$x" = "b" ]; then
      audioMusic
    else
      :
    fi
    fi
else

if [ "$n" = "b" ]; then
    echo "a. Video"
    echo "b. Video Removed Silence"
    read x
    if [ "$x" = "a" ]; then
      video
    else
    if [ "$x" = "b" ]; then
      videoSilenceRemove
    else
      :
    fi
    fi
fi
fi
fi
termux-wake-unlock
